//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.UI.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolManagement.UI.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnglishDescription.
        /// </summary>
        public static string fieldDescription {
            get {
                return ResourceManager.GetString("fieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group.EnglishName.
        /// </summary>
        public static string fieldGroupName {
            get {
                return ResourceManager.GetString("fieldGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnglishName.
        /// </summary>
        public static string fieldName {
            get {
                return ResourceManager.GetString("fieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject.EnglishName.
        /// </summary>
        public static string fieldSubjectName {
            get {
                return ResourceManager.GetString("fieldSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account.
        /// </summary>
        public static string labelAccount {
            get {
                return ResourceManager.GetString("labelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string labelAdd {
            get {
                return ResourceManager.GetString("labelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string labelAdddress {
            get {
                return ResourceManager.GetString("labelAdddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string labelAdministration {
            get {
                return ResourceManager.GetString("labelAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        public static string labelAmount {
            get {
                return ResourceManager.GetString("labelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appreciation.
        /// </summary>
        public static string labelAppreciation {
            get {
                return ResourceManager.GetString("labelAppreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birth date.
        /// </summary>
        public static string labelBirthDate {
            get {
                return ResourceManager.GetString("labelBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book model.
        /// </summary>
        public static string labelBookModel {
            get {
                return ResourceManager.GetString("labelBookModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string labelCancel {
            get {
                return ResourceManager.GetString("labelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cash flow.
        /// </summary>
        public static string labelCashFlow {
            get {
                return ResourceManager.GetString("labelCashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of cash flow.
        /// </summary>
        public static string labelCashFlowType {
            get {
                return ResourceManager.GetString("labelCashFlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Types of cash flow.
        /// </summary>
        public static string labelCashFlowTypes {
            get {
                return ResourceManager.GetString("labelCashFlowTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        public static string labelCategory {
            get {
                return ResourceManager.GetString("labelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class.
        /// </summary>
        public static string labelClass {
            get {
                return ResourceManager.GetString("labelClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class group.
        /// </summary>
        public static string labelClassGroup {
            get {
                return ResourceManager.GetString("labelClassGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class groups.
        /// </summary>
        public static string labelClassGroups {
            get {
                return ResourceManager.GetString("labelClassGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classes.
        /// </summary>
        public static string labelClasss {
            get {
                return ResourceManager.GetString("labelClasss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closed.
        /// </summary>
        public static string labelClosed {
            get {
                return ResourceManager.GetString("labelClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string labelCode {
            get {
                return ResourceManager.GetString("labelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        public static string labelConnection {
            get {
                return ResourceManager.GetString("labelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default module.
        /// </summary>
        public static string labelDefaultModule {
            get {
                return ResourceManager.GetString("labelDefaultModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delay.
        /// </summary>
        public static string labelDelay {
            get {
                return ResourceManager.GetString("labelDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string labelDelete {
            get {
                return ResourceManager.GetString("labelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string labelDesignation {
            get {
                return ResourceManager.GetString("labelDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discipline.
        /// </summary>
        public static string labelDiscipline {
            get {
                return ResourceManager.GetString("labelDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain.
        /// </summary>
        public static string labelDomain {
            get {
                return ResourceManager.GetString("labelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration.
        /// </summary>
        public static string labelDuration {
            get {
                return ResourceManager.GetString("labelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string labelEdit {
            get {
                return ResourceManager.GetString("labelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee.
        /// </summary>
        public static string labelEmployee {
            get {
                return ResourceManager.GetString("labelEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee group.
        /// </summary>
        public static string labelEmployeeGroup {
            get {
                return ResourceManager.GetString("labelEmployeeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee groups.
        /// </summary>
        public static string labelEmployeeGroups {
            get {
                return ResourceManager.GetString("labelEmployeeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee Id.
        /// </summary>
        public static string labelEmployeeId {
            get {
                return ResourceManager.GetString("labelEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        public static string labelEnd {
            get {
                return ResourceManager.GetString("labelEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Start 1ˢᵗ quarter.
        /// </summary>
        public static string labelEndFirstQuarter {
            get {
                return ResourceManager.GetString("labelEndFirstQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End 2ⁿᵈ quarter.
        /// </summary>
        public static string labelEndSecondQuarter {
            get {
                return ResourceManager.GetString("labelEndSecondQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End 3ʳᵈ quarter.
        /// </summary>
        public static string labelEndThirdQuarter {
            get {
                return ResourceManager.GetString("labelEndThirdQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English appreciation.
        /// </summary>
        public static string labelEnglishAppreciation {
            get {
                return ResourceManager.GetString("labelEnglishAppreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English description.
        /// </summary>
        public static string labelEnglishDescription {
            get {
                return ResourceManager.GetString("labelEnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English name.
        /// </summary>
        public static string labelEnglishName {
            get {
                return ResourceManager.GetString("labelEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll.
        /// </summary>
        public static string labelEnroll {
            get {
                return ResourceManager.GetString("labelEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation session.
        /// </summary>
        public static string labelEvaluationSession {
            get {
                return ResourceManager.GetString("labelEvaluationSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation sessions.
        /// </summary>
        public static string labelEvaluationSessions {
            get {
                return ResourceManager.GetString("labelEvaluationSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exigible.
        /// </summary>
        public static string labelExigible {
            get {
                return ResourceManager.GetString("labelExigible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string labelExport {
            get {
                return ResourceManager.GetString("labelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fees payable.
        /// </summary>
        public static string labelFeePayable {
            get {
                return ResourceManager.GetString("labelFeePayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fee type.
        /// </summary>
        public static string labelFeeType {
            get {
                return ResourceManager.GetString("labelFeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string labelFirstName {
            get {
                return ResourceManager.GetString("labelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French appreciation.
        /// </summary>
        public static string labelFrenchAppreciation {
            get {
                return ResourceManager.GetString("labelFrenchAppreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French description.
        /// </summary>
        public static string labelFrenchDescription {
            get {
                return ResourceManager.GetString("labelFrenchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French name.
        /// </summary>
        public static string labelFrenchName {
            get {
                return ResourceManager.GetString("labelFrenchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group.
        /// </summary>
        public static string labelGroup {
            get {
                return ResourceManager.GetString("labelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hiring date.
        /// </summary>
        public static string labelHiringDate {
            get {
                return ResourceManager.GetString("labelHiringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string labelHome {
            get {
                return ResourceManager.GetString("labelHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id Card.
        /// </summary>
        public static string labelIdCard {
            get {
                return ResourceManager.GetString("labelIdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input.
        /// </summary>
        public static string labelInput {
            get {
                return ResourceManager.GetString("labelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installments count.
        /// </summary>
        public static string labelInstallmentCount {
            get {
                return ResourceManager.GetString("labelInstallmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installments.
        /// </summary>
        public static string labelInstallments {
            get {
                return ResourceManager.GetString("labelInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        public static string labelJob {
            get {
                return ResourceManager.GetString("labelJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs.
        /// </summary>
        public static string labelJobs {
            get {
                return ResourceManager.GetString("labelJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string labelLangue {
            get {
                return ResourceManager.GetString("labelLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        public static string labelLastName {
            get {
                return ResourceManager.GetString("labelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        public static string labelLogOut {
            get {
                return ResourceManager.GetString("labelLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail.
        /// </summary>
        public static string labelMail {
            get {
                return ResourceManager.GetString("labelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark system.
        /// </summary>
        public static string labelMarkSystem {
            get {
                return ResourceManager.GetString("labelMarkSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark systems.
        /// </summary>
        public static string labelMarkSystems {
            get {
                return ResourceManager.GetString("labelMarkSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max mark.
        /// </summary>
        public static string labelMaxNote {
            get {
                return ResourceManager.GetString("labelMaxNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Min Mark.
        /// </summary>
        public static string labelMinNote {
            get {
                return ResourceManager.GetString("labelMinNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country.
        /// </summary>
        public static string labelNativeCountry {
            get {
                return ResourceManager.GetString("labelNativeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Noted on.
        /// </summary>
        public static string labelNotedOn {
            get {
                return ResourceManager.GetString("labelNotedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opened.
        /// </summary>
        public static string labelOpened {
            get {
                return ResourceManager.GetString("labelOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        public static string labelOutput {
            get {
                return ResourceManager.GetString("labelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment mean.
        /// </summary>
        public static string labelPaymentMean {
            get {
                return ResourceManager.GetString("labelPaymentMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment means.
        /// </summary>
        public static string labelPaymentMeans {
            get {
                return ResourceManager.GetString("labelPaymentMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        public static string labelPhone {
            get {
                return ResourceManager.GetString("labelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reason.
        /// </summary>
        public static string labelReason {
            get {
                return ResourceManager.GetString("labelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Religion.
        /// </summary>
        public static string labelReligion {
            get {
                return ResourceManager.GetString("labelReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reports.
        /// </summary>
        public static string labelReports {
            get {
                return ResourceManager.GetString("labelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Room.
        /// </summary>
        public static string labelRoom {
            get {
                return ResourceManager.GetString("labelRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rooms.
        /// </summary>
        public static string labelRooms {
            get {
                return ResourceManager.GetString("labelRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salary.
        /// </summary>
        public static string labelSalary {
            get {
                return ResourceManager.GetString("labelSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string labelSave {
            get {
                return ResourceManager.GetString("labelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuition fees.
        /// </summary>
        public static string labelSchoolingFee {
            get {
                return ResourceManager.GetString("labelSchoolingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School year.
        /// </summary>
        public static string labelSchoolYear {
            get {
                return ResourceManager.GetString("labelSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School years.
        /// </summary>
        public static string labelSchoolYears {
            get {
                return ResourceManager.GetString("labelSchoolYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        public static string labelSequence {
            get {
                return ResourceManager.GetString("labelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string labelSettings {
            get {
                return ResourceManager.GetString("labelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sex.
        /// </summary>
        public static string labelSex {
            get {
                return ResourceManager.GetString("labelSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string labelStart {
            get {
                return ResourceManager.GetString("labelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start 1ˢᵗ quarter.
        /// </summary>
        public static string labelStartFirstQuarter {
            get {
                return ResourceManager.GetString("labelStartFirstQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start 2ⁿᵈ quarter.
        /// </summary>
        public static string labelStartSecondQuarter {
            get {
                return ResourceManager.GetString("labelStartSecondQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start 3ʳᵈ quarter.
        /// </summary>
        public static string labelStartThirdQuarter {
            get {
                return ResourceManager.GetString("labelStartThirdQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string labelStatut {
            get {
                return ResourceManager.GetString("labelStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student.
        /// </summary>
        public static string labelStudent {
            get {
                return ResourceManager.GetString("labelStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total student.
        /// </summary>
        public static string labelStudentCount {
            get {
                return ResourceManager.GetString("labelStudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student Id.
        /// </summary>
        public static string labelStudentId {
            get {
                return ResourceManager.GetString("labelStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School marks.
        /// </summary>
        public static string labelStudentNotes {
            get {
                return ResourceManager.GetString("labelStudentNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Students.
        /// </summary>
        public static string labelStudents {
            get {
                return ResourceManager.GetString("labelStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject.
        /// </summary>
        public static string labelSubject {
            get {
                return ResourceManager.GetString("labelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject group.
        /// </summary>
        public static string labelSubjectGroup {
            get {
                return ResourceManager.GetString("labelSubjectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject groups.
        /// </summary>
        public static string labelSubjectGroups {
            get {
                return ResourceManager.GetString("labelSubjectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subjects.
        /// </summary>
        public static string labelSubjects {
            get {
                return ResourceManager.GetString("labelSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subjects taught.
        /// </summary>
        public static string labelSubjectTaught {
            get {
                return ResourceManager.GetString("labelSubjectTaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription.
        /// </summary>
        public static string labelSubscription {
            get {
                return ResourceManager.GetString("labelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription fees.
        /// </summary>
        public static string labelSubscriptionFee {
            get {
                return ResourceManager.GetString("labelSubscriptionFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TimeTable .
        /// </summary>
        public static string labelTimeTable {
            get {
                return ResourceManager.GetString("labelTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total modules.
        /// </summary>
        public static string labelTotalModule {
            get {
                return ResourceManager.GetString("labelTotalModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total tranche.
        /// </summary>
        public static string labelTrancheNumber {
            get {
                return ResourceManager.GetString("labelTrancheNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string labelType {
            get {
                return ResourceManager.GetString("labelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string labelUpdate {
            get {
                return ResourceManager.GetString("labelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name.
        /// </summary>
        public static string labelUserName {
            get {
                return ResourceManager.GetString("labelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string labelUsers {
            get {
                return ResourceManager.GetString("labelUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate school year.
        /// </summary>
        public static string messageActivateSchoolYear {
            get {
                return ResourceManager.GetString("messageActivateSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to activate the school year.
        /// </summary>
        public static string messageAskActivateSchoolYear {
            get {
                return ResourceManager.GetString("messageAskActivateSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to close the school year.
        /// </summary>
        public static string messageAskCloseSchoolYear {
            get {
                return ResourceManager.GetString("messageAskCloseSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change your password.
        /// </summary>
        public static string messageChangePassword {
            get {
                return ResourceManager.GetString("messageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a cashflow type.
        /// </summary>
        public static string messageClickToAddCashflowType {
            get {
                return ResourceManager.GetString("messageClickToAddCashflowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a class.
        /// </summary>
        public static string messageClickToAddClass {
            get {
                return ResourceManager.GetString("messageClickToAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add an employee.
        /// </summary>
        public static string messageClickToAddEmployee {
            get {
                return ResourceManager.GetString("messageClickToAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add an evaluation session.
        /// </summary>
        public static string messageClickToAddEvaluationSession {
            get {
                return ResourceManager.GetString("messageClickToAddEvaluationSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a group.
        /// </summary>
        public static string messageClickToAddGroup {
            get {
                return ResourceManager.GetString("messageClickToAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a job.
        /// </summary>
        public static string messageClickToAddJob {
            get {
                return ResourceManager.GetString("messageClickToAddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a mark system.
        /// </summary>
        public static string messageClickToAddMarkSystem {
            get {
                return ResourceManager.GetString("messageClickToAddMarkSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a payment mean.
        /// </summary>
        public static string messageClickToAddPaymentMean {
            get {
                return ResourceManager.GetString("messageClickToAddPaymentMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a room.
        /// </summary>
        public static string messageClickToAddRoom {
            get {
                return ResourceManager.GetString("messageClickToAddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a schooling fee.
        /// </summary>
        public static string messageClickToAddSchoolingFee {
            get {
                return ResourceManager.GetString("messageClickToAddSchoolingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a school year.
        /// </summary>
        public static string messageClickToAddSchoolYear {
            get {
                return ResourceManager.GetString("messageClickToAddSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a student.
        /// </summary>
        public static string messageClickToAddStudent {
            get {
                return ResourceManager.GetString("messageClickToAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a subject.
        /// </summary>
        public static string messageClickToAddSubject {
            get {
                return ResourceManager.GetString("messageClickToAddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a subscription fee.
        /// </summary>
        public static string messageClickToAddSubscriptionFee {
            get {
                return ResourceManager.GetString("messageClickToAddSubscriptionFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a user.
        /// </summary>
        public static string messageClickToAddUser {
            get {
                return ResourceManager.GetString("messageClickToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to export.
        /// </summary>
        public static string messageClickToExport {
            get {
                return ResourceManager.GetString("messageClickToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to print.
        /// </summary>
        public static string messageClickToPrint {
            get {
                return ResourceManager.GetString("messageClickToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to see.
        /// </summary>
        public static string messageClickToSee {
            get {
                return ResourceManager.GetString("messageClickToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close the school year.
        /// </summary>
        public static string messageCloseSchoolYear {
            get {
                return ResourceManager.GetString("messageCloseSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search ....
        /// </summary>
        public static string messageResearch {
            get {
                return ResourceManager.GetString("messageResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search module ....
        /// </summary>
        public static string messageSearchModule {
            get {
                return ResourceManager.GetString("messageSearchModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activation successfully completed.
        /// </summary>
        public static string messageSuccesActivateSchoolYear {
            get {
                return ResourceManager.GetString("messageSuccesActivateSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closing successfully completed.
        /// </summary>
        public static string messageSuccesCloseSchoolYear {
            get {
                return ResourceManager.GetString("messageSuccesCloseSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of subject.
        /// </summary>
        public static string titleSubjectList {
            get {
                return ResourceManager.GetString("titleSubjectList", resourceCulture);
            }
        }
    }
}
