//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolManagement.UI.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnglishDescription.
        /// </summary>
        public static string fieldDescription {
            get {
                return ResourceManager.GetString("fieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group.EnglishName.
        /// </summary>
        public static string fieldGroupName {
            get {
                return ResourceManager.GetString("fieldGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EnglishName.
        /// </summary>
        public static string fieldName {
            get {
                return ResourceManager.GetString("fieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject.EnglishName.
        /// </summary>
        public static string fieldSubjectName {
            get {
                return ResourceManager.GetString("fieldSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account.
        /// </summary>
        public static string labelAccount {
            get {
                return ResourceManager.GetString("labelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string labelAdd {
            get {
                return ResourceManager.GetString("labelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string labelAdddress {
            get {
                return ResourceManager.GetString("labelAdddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding.
        /// </summary>
        public static string labelAdding {
            get {
                return ResourceManager.GetString("labelAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add picture.
        /// </summary>
        public static string labelAddPicture {
            get {
                return ResourceManager.GetString("labelAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string labelAdministration {
            get {
                return ResourceManager.GetString("labelAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        public static string labelAmount {
            get {
                return ResourceManager.GetString("labelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount tuition.
        /// </summary>
        public static string labelAmountTuition {
            get {
                return ResourceManager.GetString("labelAmountTuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appreciation.
        /// </summary>
        public static string labelAppreciation {
            get {
                return ResourceManager.GetString("labelAppreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assign.
        /// </summary>
        public static string labelAssign {
            get {
                return ResourceManager.GetString("labelAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attendance.
        /// </summary>
        public static string labelAttendance {
            get {
                return ResourceManager.GetString("labelAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attendances.
        /// </summary>
        public static string labelAttendances {
            get {
                return ResourceManager.GetString("labelAttendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birth date.
        /// </summary>
        public static string labelBirthDate {
            get {
                return ResourceManager.GetString("labelBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birth place.
        /// </summary>
        public static string labelBirthPlace {
            get {
                return ResourceManager.GetString("labelBirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Book model.
        /// </summary>
        public static string labelBookModel {
            get {
                return ResourceManager.GetString("labelBookModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Born on.
        /// </summary>
        public static string labelBornOn {
            get {
                return ResourceManager.GetString("labelBornOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string labelCancel {
            get {
                return ResourceManager.GetString("labelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cash flow.
        /// </summary>
        public static string labelCashFlow {
            get {
                return ResourceManager.GetString("labelCashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of cash flow.
        /// </summary>
        public static string labelCashFlowType {
            get {
                return ResourceManager.GetString("labelCashFlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Types of cash flow.
        /// </summary>
        public static string labelCashFlowTypes {
            get {
                return ResourceManager.GetString("labelCashFlowTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        public static string labelCategory {
            get {
                return ResourceManager.GetString("labelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check all.
        /// </summary>
        public static string labelCheckAll {
            get {
                return ResourceManager.GetString("labelCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class.
        /// </summary>
        public static string labelClass {
            get {
                return ResourceManager.GetString("labelClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class group.
        /// </summary>
        public static string labelClassGroup {
            get {
                return ResourceManager.GetString("labelClassGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class groups.
        /// </summary>
        public static string labelClassGroups {
            get {
                return ResourceManager.GetString("labelClassGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classes.
        /// </summary>
        public static string labelClasss {
            get {
                return ResourceManager.GetString("labelClasss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closed.
        /// </summary>
        public static string labelClosed {
            get {
                return ResourceManager.GetString("labelClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string labelCode {
            get {
                return ResourceManager.GetString("labelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coefficient.
        /// </summary>
        public static string labelCoefficient {
            get {
                return ResourceManager.GetString("labelCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        public static string labelConnection {
            get {
                return ResourceManager.GetString("labelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string labelContact {
            get {
                return ResourceManager.GetString("labelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacts.
        /// </summary>
        public static string labelContacts {
            get {
                return ResourceManager.GetString("labelContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        public static string labelDay {
            get {
                return ResourceManager.GetString("labelDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default module.
        /// </summary>
        public static string labelDefaultModule {
            get {
                return ResourceManager.GetString("labelDefaultModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delay.
        /// </summary>
        public static string labelDelay {
            get {
                return ResourceManager.GetString("labelDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string labelDelete {
            get {
                return ResourceManager.GetString("labelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deletion.
        /// </summary>
        public static string labelDeletion {
            get {
                return ResourceManager.GetString("labelDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string labelDesignation {
            get {
                return ResourceManager.GetString("labelDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disciplinary record.
        /// </summary>
        public static string labelDisciplinaryRecord {
            get {
                return ResourceManager.GetString("labelDisciplinaryRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disciplinary sheet.
        /// </summary>
        public static string labelDisciplinarySheet {
            get {
                return ResourceManager.GetString("labelDisciplinarySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discipline.
        /// </summary>
        public static string labelDiscipline {
            get {
                return ResourceManager.GetString("labelDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disciplines.
        /// </summary>
        public static string labelDisciplines {
            get {
                return ResourceManager.GetString("labelDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discount.
        /// </summary>
        public static string labelDiscount {
            get {
                return ResourceManager.GetString("labelDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain.
        /// </summary>
        public static string labelDomain {
            get {
                return ResourceManager.GetString("labelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate for current year.
        /// </summary>
        public static string labelDuplicateForCurrentYear {
            get {
                return ResourceManager.GetString("labelDuplicateForCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration.
        /// </summary>
        public static string labelDuration {
            get {
                return ResourceManager.GetString("labelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string labelEdit {
            get {
                return ResourceManager.GetString("labelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee.
        /// </summary>
        public static string labelEmployee {
            get {
                return ResourceManager.GetString("labelEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee&apos;s account.
        /// </summary>
        public static string labelEmployeeAccount {
            get {
                return ResourceManager.GetString("labelEmployeeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee group.
        /// </summary>
        public static string labelEmployeeGroup {
            get {
                return ResourceManager.GetString("labelEmployeeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee groups.
        /// </summary>
        public static string labelEmployeeGroups {
            get {
                return ResourceManager.GetString("labelEmployeeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee Id.
        /// </summary>
        public static string labelEmployeeId {
            get {
                return ResourceManager.GetString("labelEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        public static string labelEnd {
            get {
                return ResourceManager.GetString("labelEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Start 1ˢᵗ quarter.
        /// </summary>
        public static string labelEndFirstQuarter {
            get {
                return ResourceManager.GetString("labelEndFirstQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End hour.
        /// </summary>
        public static string labelEndHour {
            get {
                return ResourceManager.GetString("labelEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End 2ⁿᵈ quarter.
        /// </summary>
        public static string labelEndSecondQuarter {
            get {
                return ResourceManager.GetString("labelEndSecondQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End 3ʳᵈ quarter.
        /// </summary>
        public static string labelEndThirdQuarter {
            get {
                return ResourceManager.GetString("labelEndThirdQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English appreciation.
        /// </summary>
        public static string labelEnglishAppreciation {
            get {
                return ResourceManager.GetString("labelEnglishAppreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English description.
        /// </summary>
        public static string labelEnglishDescription {
            get {
                return ResourceManager.GetString("labelEnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English name.
        /// </summary>
        public static string labelEnglishName {
            get {
                return ResourceManager.GetString("labelEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enroll.
        /// </summary>
        public static string labelEnroll {
            get {
                return ResourceManager.GetString("labelEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enrolling date.
        /// </summary>
        public static string labelEnrollingDate {
            get {
                return ResourceManager.GetString("labelEnrollingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation session.
        /// </summary>
        public static string labelEvaluationSession {
            get {
                return ResourceManager.GetString("labelEvaluationSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluation sessions.
        /// </summary>
        public static string labelEvaluationSessions {
            get {
                return ResourceManager.GetString("labelEvaluationSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exigible.
        /// </summary>
        public static string labelExigible {
            get {
                return ResourceManager.GetString("labelExigible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string labelExport {
            get {
                return ResourceManager.GetString("labelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fees payable.
        /// </summary>
        public static string labelFeePayable {
            get {
                return ResourceManager.GetString("labelFeePayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fee type.
        /// </summary>
        public static string labelFeeType {
            get {
                return ResourceManager.GetString("labelFeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string labelFirstName {
            get {
                return ResourceManager.GetString("labelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French appreciation.
        /// </summary>
        public static string labelFrenchAppreciation {
            get {
                return ResourceManager.GetString("labelFrenchAppreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French description.
        /// </summary>
        public static string labelFrenchDescription {
            get {
                return ResourceManager.GetString("labelFrenchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French name.
        /// </summary>
        public static string labelFrenchName {
            get {
                return ResourceManager.GetString("labelFrenchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full name.
        /// </summary>
        public static string labelFullName {
            get {
                return ResourceManager.GetString("labelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate empty class report.
        /// </summary>
        public static string labelGenerateEmptyClassReport {
            get {
                return ResourceManager.GetString("labelGenerateEmptyClassReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group.
        /// </summary>
        public static string labelGroup {
            get {
                return ResourceManager.GetString("labelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health.
        /// </summary>
        public static string labelHealth {
            get {
                return ResourceManager.GetString("labelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health record.
        /// </summary>
        public static string labelHealthRecord {
            get {
                return ResourceManager.GetString("labelHealthRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Healthe status.
        /// </summary>
        public static string labelHealthStatus {
            get {
                return ResourceManager.GetString("labelHealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hired on.
        /// </summary>
        public static string labelHiredOn {
            get {
                return ResourceManager.GetString("labelHiredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hiring date.
        /// </summary>
        public static string labelHiringDate {
            get {
                return ResourceManager.GetString("labelHiringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string labelHome {
            get {
                return ResourceManager.GetString("labelHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id Card.
        /// </summary>
        public static string labelIdCard {
            get {
                return ResourceManager.GetString("labelIdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id Number.
        /// </summary>
        public static string labelIdNumber {
            get {
                return ResourceManager.GetString("labelIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transaction Id.
        /// </summary>
        public static string labelIdTransaction {
            get {
                return ResourceManager.GetString("labelIdTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        public static string labelImport {
            get {
                return ResourceManager.GetString("labelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input.
        /// </summary>
        public static string labelInput {
            get {
                return ResourceManager.GetString("labelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insolvency.
        /// </summary>
        public static string labelInsolvency {
            get {
                return ResourceManager.GetString("labelInsolvency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installments count.
        /// </summary>
        public static string labelInstallmentCount {
            get {
                return ResourceManager.GetString("labelInstallmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installments.
        /// </summary>
        public static string labelInstallments {
            get {
                return ResourceManager.GetString("labelInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        public static string labelJob {
            get {
                return ResourceManager.GetString("labelJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs.
        /// </summary>
        public static string labelJobs {
            get {
                return ResourceManager.GetString("labelJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string labelLangue {
            get {
                return ResourceManager.GetString("labelLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        public static string labelLastName {
            get {
                return ResourceManager.GetString("labelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log In.
        /// </summary>
        public static string labelLogIn {
            get {
                return ResourceManager.GetString("labelLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        public static string labelLogOut {
            get {
                return ResourceManager.GetString("labelLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail.
        /// </summary>
        public static string labelMail {
            get {
                return ResourceManager.GetString("labelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark system.
        /// </summary>
        public static string labelMarkSystem {
            get {
                return ResourceManager.GetString("labelMarkSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mark systems.
        /// </summary>
        public static string labelMarkSystems {
            get {
                return ResourceManager.GetString("labelMarkSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Master teacher.
        /// </summary>
        public static string labelMasterTeacher {
            get {
                return ResourceManager.GetString("labelMasterTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max mark.
        /// </summary>
        public static string labelMaxNote {
            get {
                return ResourceManager.GetString("labelMaxNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Min Mark.
        /// </summary>
        public static string labelMinNote {
            get {
                return ResourceManager.GetString("labelMinNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module.
        /// </summary>
        public static string labelModule {
            get {
                return ResourceManager.GetString("labelModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modules.
        /// </summary>
        public static string labelModules {
            get {
                return ResourceManager.GetString("labelModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More information.
        /// </summary>
        public static string labelMoreInfo {
            get {
                return ResourceManager.GetString("labelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country.
        /// </summary>
        public static string labelNativeCountry {
            get {
                return ResourceManager.GetString("labelNativeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password.
        /// </summary>
        public static string labelNewPasswors {
            get {
                return ResourceManager.GetString("labelNewPasswors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        public static string labelNote {
            get {
                return ResourceManager.GetString("labelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Noted on.
        /// </summary>
        public static string labelNotedOn {
            get {
                return ResourceManager.GetString("labelNotedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes.
        /// </summary>
        public static string labelNotes {
            get {
                return ResourceManager.GetString("labelNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note&apos;s subject.
        /// </summary>
        public static string labelNoteSubject {
            get {
                return ResourceManager.GetString("labelNoteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old password.
        /// </summary>
        public static string labelOldPassword {
            get {
                return ResourceManager.GetString("labelOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opened.
        /// </summary>
        public static string labelOpened {
            get {
                return ResourceManager.GetString("labelOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        public static string labelOutput {
            get {
                return ResourceManager.GetString("labelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paid.
        /// </summary>
        public static string labelPaid {
            get {
                return ResourceManager.GetString("labelPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment mean.
        /// </summary>
        public static string labelPaymentMean {
            get {
                return ResourceManager.GetString("labelPaymentMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment means.
        /// </summary>
        public static string labelPaymentMeans {
            get {
                return ResourceManager.GetString("labelPaymentMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        public static string labelPhone {
            get {
                return ResourceManager.GetString("labelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Population by group.
        /// </summary>
        public static string labelPopulationByGroup {
            get {
                return ResourceManager.GetString("labelPopulationByGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        public static string labelPrint {
            get {
                return ResourceManager.GetString("labelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Printing.
        /// </summary>
        public static string labelPrinting {
            get {
                return ResourceManager.GetString("labelPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read.
        /// </summary>
        public static string labelRead {
            get {
                return ResourceManager.GetString("labelRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reason.
        /// </summary>
        public static string labelReason {
            get {
                return ResourceManager.GetString("labelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registered On.
        /// </summary>
        public static string labelRegisteredOn {
            get {
                return ResourceManager.GetString("labelRegisteredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Religion.
        /// </summary>
        public static string labelReligion {
            get {
                return ResourceManager.GetString("labelReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reports.
        /// </summary>
        public static string labelReports {
            get {
                return ResourceManager.GetString("labelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return.
        /// </summary>
        public static string labelReturn {
            get {
                return ResourceManager.GetString("labelReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Room.
        /// </summary>
        public static string labelRoom {
            get {
                return ResourceManager.GetString("labelRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rooms.
        /// </summary>
        public static string labelRooms {
            get {
                return ResourceManager.GetString("labelRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salary.
        /// </summary>
        public static string labelSalary {
            get {
                return ResourceManager.GetString("labelSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done.
        /// </summary>
        public static string labelSateDone {
            get {
                return ResourceManager.GetString("labelSateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not done.
        /// </summary>
        public static string labelSateNoDone {
            get {
                return ResourceManager.GetString("labelSateNoDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string labelSave {
            get {
                return ResourceManager.GetString("labelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuition fees.
        /// </summary>
        public static string labelSchoolingFee {
            get {
                return ResourceManager.GetString("labelSchoolingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School year.
        /// </summary>
        public static string labelSchoolYear {
            get {
                return ResourceManager.GetString("labelSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School years.
        /// </summary>
        public static string labelSchoolYears {
            get {
                return ResourceManager.GetString("labelSchoolYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Section.
        /// </summary>
        public static string labelSection {
            get {
                return ResourceManager.GetString("labelSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string labelSelectAll {
            get {
                return ResourceManager.GetString("labelSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        public static string labelSequence {
            get {
                return ResourceManager.GetString("labelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string labelSettings {
            get {
                return ResourceManager.GetString("labelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sex.
        /// </summary>
        public static string labelSex {
            get {
                return ResourceManager.GetString("labelSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign In.
        /// </summary>
        public static string labelSignIn {
            get {
                return ResourceManager.GetString("labelSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solvency.
        /// </summary>
        public static string labelSolvency {
            get {
                return ResourceManager.GetString("labelSolvency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string labelStart {
            get {
                return ResourceManager.GetString("labelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start 1ˢᵗ quarter.
        /// </summary>
        public static string labelStartFirstQuarter {
            get {
                return ResourceManager.GetString("labelStartFirstQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start hour.
        /// </summary>
        public static string labelStartHour {
            get {
                return ResourceManager.GetString("labelStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start 2ⁿᵈ quarter.
        /// </summary>
        public static string labelStartSecondQuarter {
            get {
                return ResourceManager.GetString("labelStartSecondQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start 3ʳᵈ quarter.
        /// </summary>
        public static string labelStartThirdQuarter {
            get {
                return ResourceManager.GetString("labelStartThirdQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string labelStateCancel {
            get {
                return ResourceManager.GetString("labelStateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ongoing.
        /// </summary>
        public static string labelStateOngoing {
            get {
                return ResourceManager.GetString("labelStateOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To do.
        /// </summary>
        public static string labelStateToDo {
            get {
                return ResourceManager.GetString("labelStateToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string labelStatut {
            get {
                return ResourceManager.GetString("labelStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student.
        /// </summary>
        public static string labelStudent {
            get {
                return ResourceManager.GetString("labelStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student&apos;s account.
        /// </summary>
        public static string labelStudentAccount {
            get {
                return ResourceManager.GetString("labelStudentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total student.
        /// </summary>
        public static string labelStudentCount {
            get {
                return ResourceManager.GetString("labelStudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student Id.
        /// </summary>
        public static string labelStudentId {
            get {
                return ResourceManager.GetString("labelStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        public static string labelStudentLeft {
            get {
                return ResourceManager.GetString("labelStudentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School marks.
        /// </summary>
        public static string labelStudentNotes {
            get {
                return ResourceManager.GetString("labelStudentNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Students.
        /// </summary>
        public static string labelStudents {
            get {
                return ResourceManager.GetString("labelStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Students by class.
        /// </summary>
        public static string labelStudentsByClass {
            get {
                return ResourceManager.GetString("labelStudentsByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Students by group.
        /// </summary>
        public static string labelStudentsByGroup {
            get {
                return ResourceManager.GetString("labelStudentsByGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Students by status.
        /// </summary>
        public static string labelStudentsByStatus {
            get {
                return ResourceManager.GetString("labelStudentsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Present.
        /// </summary>
        public static string labelStudentsNoLeft {
            get {
                return ResourceManager.GetString("labelStudentsNoLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject.
        /// </summary>
        public static string labelSubject {
            get {
                return ResourceManager.GetString("labelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject group.
        /// </summary>
        public static string labelSubjectGroup {
            get {
                return ResourceManager.GetString("labelSubjectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject groups.
        /// </summary>
        public static string labelSubjectGroups {
            get {
                return ResourceManager.GetString("labelSubjectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subjects.
        /// </summary>
        public static string labelSubjects {
            get {
                return ResourceManager.GetString("labelSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subjects taught.
        /// </summary>
        public static string labelSubjectTaught {
            get {
                return ResourceManager.GetString("labelSubjectTaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription.
        /// </summary>
        public static string labelSubscription {
            get {
                return ResourceManager.GetString("labelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription fees.
        /// </summary>
        public static string labelSubscriptionFee {
            get {
                return ResourceManager.GetString("labelSubscriptionFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscriptions.
        /// </summary>
        public static string labelSubscriptions {
            get {
                return ResourceManager.GetString("labelSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher.
        /// </summary>
        public static string labelTeacher {
            get {
                return ResourceManager.GetString("labelTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher in.
        /// </summary>
        public static string labelTeacherIn {
            get {
                return ResourceManager.GetString("labelTeacherIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teacher out.
        /// </summary>
        public static string labelTeacherOut {
            get {
                return ResourceManager.GetString("labelTeacherOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timesheet.
        /// </summary>
        public static string labelTimesheet {
            get {
                return ResourceManager.GetString("labelTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TimeTable .
        /// </summary>
        public static string labelTimeTable {
            get {
                return ResourceManager.GetString("labelTimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total modules.
        /// </summary>
        public static string labelTotalModule {
            get {
                return ResourceManager.GetString("labelTotalModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total tranche.
        /// </summary>
        public static string labelTrancheNumber {
            get {
                return ResourceManager.GetString("labelTrancheNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuition fees.
        /// </summary>
        public static string labelTuitionFees {
            get {
                return ResourceManager.GetString("labelTuitionFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string labelType {
            get {
                return ResourceManager.GetString("labelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        public static string labelTypeJob {
            get {
                return ResourceManager.GetString("labelTypeJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs.
        /// </summary>
        public static string labelTypeJobs {
            get {
                return ResourceManager.GetString("labelTypeJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à uncheck all.
        /// </summary>
        public static string labelUnCheckAll {
            get {
                return ResourceManager.GetString("labelUnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unpaid.
        /// </summary>
        public static string labelUnPaid {
            get {
                return ResourceManager.GetString("labelUnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string labelUpdate {
            get {
                return ResourceManager.GetString("labelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User modules.
        /// </summary>
        public static string labelUserModule {
            get {
                return ResourceManager.GetString("labelUserModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name.
        /// </summary>
        public static string labelUserName {
            get {
                return ResourceManager.GetString("labelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User rooms.
        /// </summary>
        public static string labelUserRoom {
            get {
                return ResourceManager.GetString("labelUserRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string labelUsers {
            get {
                return ResourceManager.GetString("labelUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à year(s) of service.
        /// </summary>
        public static string labelYearOfService {
            get {
                return ResourceManager.GetString("labelYearOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate school year.
        /// </summary>
        public static string messageActivateSchoolYear {
            get {
                return ResourceManager.GetString("messageActivateSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add error....
        /// </summary>
        public static string messageAddError {
            get {
                return ResourceManager.GetString("messageAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to activate the school year.
        /// </summary>
        public static string messageAskActivateSchoolYear {
            get {
                return ResourceManager.GetString("messageAskActivateSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to close the school year.
        /// </summary>
        public static string messageAskCloseSchoolYear {
            get {
                return ResourceManager.GetString("messageAskCloseSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One of instalments is not correct.
        /// </summary>
        public static string messageBadInstalment {
            get {
                return ResourceManager.GetString("messageBadInstalment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old password is wrong.
        /// </summary>
        public static string messageBadOldPassword {
            get {
                return ResourceManager.GetString("messageBadOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If it is a bilingual class 0=French section and 1=English section. Otherwise the section=0.
        /// </summary>
        public static string messageBadSection {
            get {
                return ResourceManager.GetString("messageBadSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of tranches must not be more than three (3).
        /// </summary>
        public static string messageBadTrancheNumber {
            get {
                return ResourceManager.GetString("messageBadTrancheNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name or password is incorrect.
        /// </summary>
        public static string messageBaduserBadPassword {
            get {
                return ResourceManager.GetString("messageBaduserBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This cashflow already exists.
        /// </summary>
        public static string messageCashFlowExist {
            get {
                return ResourceManager.GetString("messageCashFlowExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change your password.
        /// </summary>
        public static string messageChangePassword {
            get {
                return ResourceManager.GetString("messageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This  class already exists.
        /// </summary>
        public static string messageClassExist {
            get {
                return ResourceManager.GetString("messageClassExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add.
        /// </summary>
        public static string messageClickToAdd {
            get {
                return ResourceManager.GetString("messageClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a cashflow type.
        /// </summary>
        public static string messageClickToAddCashflowType {
            get {
                return ResourceManager.GetString("messageClickToAddCashflowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a class.
        /// </summary>
        public static string messageClickToAddClass {
            get {
                return ResourceManager.GetString("messageClickToAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add an employee.
        /// </summary>
        public static string messageClickToAddEmployee {
            get {
                return ResourceManager.GetString("messageClickToAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add an evaluation session.
        /// </summary>
        public static string messageClickToAddEvaluationSession {
            get {
                return ResourceManager.GetString("messageClickToAddEvaluationSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a group.
        /// </summary>
        public static string messageClickToAddGroup {
            get {
                return ResourceManager.GetString("messageClickToAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a job.
        /// </summary>
        public static string messageClickToAddJob {
            get {
                return ResourceManager.GetString("messageClickToAddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a mark system.
        /// </summary>
        public static string messageClickToAddMarkSystem {
            get {
                return ResourceManager.GetString("messageClickToAddMarkSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a payment mean.
        /// </summary>
        public static string messageClickToAddPaymentMean {
            get {
                return ResourceManager.GetString("messageClickToAddPaymentMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a room.
        /// </summary>
        public static string messageClickToAddRoom {
            get {
                return ResourceManager.GetString("messageClickToAddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a schooling fee.
        /// </summary>
        public static string messageClickToAddSchoolingFee {
            get {
                return ResourceManager.GetString("messageClickToAddSchoolingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a school year.
        /// </summary>
        public static string messageClickToAddSchoolYear {
            get {
                return ResourceManager.GetString("messageClickToAddSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a student.
        /// </summary>
        public static string messageClickToAddStudent {
            get {
                return ResourceManager.GetString("messageClickToAddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a subject.
        /// </summary>
        public static string messageClickToAddSubject {
            get {
                return ResourceManager.GetString("messageClickToAddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a subscription fee.
        /// </summary>
        public static string messageClickToAddSubscriptionFee {
            get {
                return ResourceManager.GetString("messageClickToAddSubscriptionFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to add a user.
        /// </summary>
        public static string messageClickToAddUser {
            get {
                return ResourceManager.GetString("messageClickToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to edit.
        /// </summary>
        public static string messageClickToEdit {
            get {
                return ResourceManager.GetString("messageClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to export.
        /// </summary>
        public static string messageClickToExport {
            get {
                return ResourceManager.GetString("messageClickToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to hide password.
        /// </summary>
        public static string messageClickToHidePassword {
            get {
                return ResourceManager.GetString("messageClickToHidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to print.
        /// </summary>
        public static string messageClickToPrint {
            get {
                return ResourceManager.GetString("messageClickToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to save.
        /// </summary>
        public static string messageClickToSave {
            get {
                return ResourceManager.GetString("messageClickToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to see.
        /// </summary>
        public static string messageClickToSee {
            get {
                return ResourceManager.GetString("messageClickToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to view password.
        /// </summary>
        public static string messageClickToSeePassword {
            get {
                return ResourceManager.GetString("messageClickToSeePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close the school year.
        /// </summary>
        public static string messageCloseSchoolYear {
            get {
                return ResourceManager.GetString("messageCloseSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to delete?.
        /// </summary>
        public static string messageConfirmDelete {
            get {
                return ResourceManager.GetString("messageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to duplicate these fees for.
        /// </summary>
        public static string messageConfirmeDuplicateFee {
            get {
                return ResourceManager.GetString("messageConfirmeDuplicateFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to return this transaction ?.
        /// </summary>
        public static string messageConfirmReturn {
            get {
                return ResourceManager.GetString("messageConfirmReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete error....
        /// </summary>
        public static string messageDeleteError {
            get {
                return ResourceManager.GetString("messageDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double click here to see.
        /// </summary>
        public static string messageDoubleClickToSee {
            get {
                return ResourceManager.GetString("messageDoubleClickToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The end date must be greater than start date.
        /// </summary>
        public static string messageEndDateGreaterThanStartDate {
            get {
                return ResourceManager.GetString("messageEndDateGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The end must be greater than start.
        /// </summary>
        public static string messageEndGreaterThanStart {
            get {
                return ResourceManager.GetString("messageEndGreaterThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The end hour must be greater than start hour.
        /// </summary>
        public static string messageEndHourGreaterThanStartHour {
            get {
                return ResourceManager.GetString("messageEndHourGreaterThanStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This evaluation already exists.
        /// </summary>
        public static string messageEvaluationExist {
            get {
                return ResourceManager.GetString("messageEvaluationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fees already exist.
        /// </summary>
        public static string messageFeeAlreadyExist {
            get {
                return ResourceManager.GetString("messageFeeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These fees already exist.
        /// </summary>
        public static string messageFeesExist {
            get {
                return ResourceManager.GetString("messageFeesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill in this field.
        /// </summary>
        public static string messageFillField {
            get {
                return ResourceManager.GetString("messageFillField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This group already exists.
        /// </summary>
        public static string messageGroupExist {
            get {
                return ResourceManager.GetString("messageGroupExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This id number is already assigned.
        /// </summary>
        public static string messageIdNumberlreadyExist {
            get {
                return ResourceManager.GetString("messageIdNumberlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This job already exists.
        /// </summary>
        public static string messageJobExist {
            get {
                return ResourceManager.GetString("messageJobExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot take action with a closed school year.
        /// </summary>
        public static string messageNoActionWithClosedYear {
            get {
                return ResourceManager.GetString("messageNoActionWithClosedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This payment mean is already exists.
        /// </summary>
        public static string messagePaymentMeanExist {
            get {
                return ResourceManager.GetString("messagePaymentMeanExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This  rating system already exists.
        /// </summary>
        public static string messageRatingSystemExist {
            get {
                return ResourceManager.GetString("messageRatingSystemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This record already exist.
        /// </summary>
        public static string messageRecordExist {
            get {
                return ResourceManager.GetString("messageRecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An open school year is required!.
        /// </summary>
        public static string messageRequireOpenYear {
            get {
                return ResourceManager.GetString("messageRequireOpenYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search ....
        /// </summary>
        public static string messageResearch {
            get {
                return ResourceManager.GetString("messageResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This transaction has already been returned.
        /// </summary>
        public static string messageReturnAllreadyDone {
            get {
                return ResourceManager.GetString("messageReturnAllreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This room already exist.
        /// </summary>
        public static string messageRoomExist {
            get {
                return ResourceManager.GetString("messageRoomExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This school year is closed.
        /// </summary>
        public static string messageSchoolYearClosed {
            get {
                return ResourceManager.GetString("messageSchoolYearClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This school year already exist.
        /// </summary>
        public static string messageSchoolYearExist {
            get {
                return ResourceManager.GetString("messageSchoolYearExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search module ....
        /// </summary>
        public static string messageSearchModule {
            get {
                return ResourceManager.GetString("messageSearchModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This  subject already exists.
        /// </summary>
        public static string messageSubjectExist {
            get {
                return ResourceManager.GetString("messageSubjectExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These Subscription Fees already exist.
        /// </summary>
        public static string messageSubscriptionFeesExist {
            get {
                return ResourceManager.GetString("messageSubscriptionFeesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activation successfully completed.
        /// </summary>
        public static string messageSuccesActivateSchoolYear {
            get {
                return ResourceManager.GetString("messageSuccesActivateSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closing successfully completed.
        /// </summary>
        public static string messageSuccesCloseSchoolYear {
            get {
                return ResourceManager.GetString("messageSuccesCloseSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select or take a photo.
        /// </summary>
        public static string messageTakeSelectPicture {
            get {
                return ResourceManager.GetString("messageTakeSelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Task completed successfully.
        /// </summary>
        public static string messageTaskSuccessfully {
            get {
                return ResourceManager.GetString("messageTaskSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow cashflow.
        /// </summary>
        public static string messageUnknowCashflow {
            get {
                return ResourceManager.GetString("messageUnknowCashflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow class.
        /// </summary>
        public static string messageUnknowClass {
            get {
                return ResourceManager.GetString("messageUnknowClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown employee.
        /// </summary>
        public static string messageUnknowEmployee {
            get {
                return ResourceManager.GetString("messageUnknowEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow group.
        /// </summary>
        public static string messageUnknowGroup {
            get {
                return ResourceManager.GetString("messageUnknowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow Job.
        /// </summary>
        public static string messageUnknowJob {
            get {
                return ResourceManager.GetString("messageUnknowJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow school year.
        /// </summary>
        public static string messageUnknowSchoolYear {
            get {
                return ResourceManager.GetString("messageUnknowSchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow subject.
        /// </summary>
        public static string messageUnknowSubject {
            get {
                return ResourceManager.GetString("messageUnknowSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknow type.
        /// </summary>
        public static string messageUnknowType {
            get {
                return ResourceManager.GetString("messageUnknowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update error....
        /// </summary>
        public static string messageUpdateError {
            get {
                return ResourceManager.GetString("messageUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This user account already exists.
        /// </summary>
        public static string messageUserExist {
            get {
                return ResourceManager.GetString("messageUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attendance list.
        /// </summary>
        public static string tiltleAttendanceList {
            get {
                return ResourceManager.GetString("tiltleAttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class list.
        /// </summary>
        public static string titleClassList {
            get {
                return ResourceManager.GetString("titleClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee list.
        /// </summary>
        public static string titleEmployeeList {
            get {
                return ResourceManager.GetString("titleEmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module list.
        /// </summary>
        public static string titleModuleList {
            get {
                return ResourceManager.GetString("titleModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note list.
        /// </summary>
        public static string titleNoteList {
            get {
                return ResourceManager.GetString("titleNoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Room list.
        /// </summary>
        public static string titleRoomList {
            get {
                return ResourceManager.GetString("titleRoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à School fees.
        /// </summary>
        public static string titleSchoolFees {
            get {
                return ResourceManager.GetString("titleSchoolFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student list.
        /// </summary>
        public static string titleStudentList {
            get {
                return ResourceManager.GetString("titleStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject list.
        /// </summary>
        public static string titleSubjectList {
            get {
                return ResourceManager.GetString("titleSubjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User list.
        /// </summary>
        public static string titleUserList {
            get {
                return ResourceManager.GetString("titleUserList", resourceCulture);
            }
        }
    }
}
